name: learning_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

assets:
  - assets/images/

environment:
  sdk: ^3.9.2

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
