name: learning_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  google_fonts: ^6.2.1
  firebase_core: ^4.1.1
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  google_ml_kit: ^0.20.0
  camera: ^0.11.2
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
